// <auto-generated />
using Elect.Sample.Data.EF.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using DbContext = Elect.Sample.Data.EF.Services.DbContext;

namespace Elect.Sample.Data.EF.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20180506171321_User")]
    partial class User
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Elect.Sample.Data.EF.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<Guid?>("DeletedBy");

                    b.Property<DateTimeOffset?>("DeletedTime");

                    b.Property<Guid?>("LastUpdatedBy");

                    b.Property<DateTimeOffset>("LastUpdatedTime");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("DeletedTime");

                    b.HasIndex("Id");

                    b.HasIndex("UserName");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
